CREATE DATABASE GELADO;
USE GELADO;
CREATE TABLE IF NOT EXISTS TBL_ROLES
(
    ID_ROLE INTEGER PRIMARY KEY AUTO_INCREMENT,
    TEXTO_ROLE VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS USUARIOS
(
    ID_USUARIO INTEGER PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(100),
    SENHA VARCHAR(1000),
    ID_ROLE INTEGER
);

CREATE TABLE IF NOT EXISTS CLIENTES
(
    ID_CLIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200),
    CPF_CNPJ VARCHAR(14),
    ID_USUARIO INTEGER
);

CREATE TABLE IF NOT EXISTS TELEFONES
(
    ID_TELEFONE INTEGER PRIMARY KEY AUTO_INCREMENT,
    NUMERO_TELEFONE VARCHAR(14),
    ID_CLIENTE INTEGER
);

CREATE TABLE IF NOT EXISTS ENDERECOS
(
    ID_ENDERECO INTEGER PRIMARY KEY AUTO_INCREMENT,
    MUNICIPIO VARCHAR(100),
    BAIRRO VARCHAR(100),
    NOME_RUA VARCHAR(100),
    NUMERO INTEGER,
    CEP VARCHAR(9),
    ID_USUARIO INTEGER
);

CREATE TABLE IF NOT EXISTS PEDIDOS
(
    ID_PEDIDO INTEGER PRIMARY KEY AUTO_INCREMENT,
    DATA_PEDIDO TIMESTAMP,
    ID_CLIENTE INTEGER
);

CREATE TABLE IF NOT EXISTS ITENS_PEDIDOS
(
    ID_ITEM_PEDIDO INTEGER PRIMARY KEY AUTO_INCREMENT,
    QUANTIDADE INTEGER,
    VALOR_ITEM_PEDIDO DECIMAL(17,2),
    ID_PEDIDO INTEGER,
    ID_PRODUTO INTEGER
);

CREATE TABLE IF NOT EXISTS PRODUTOS
(
    ID_PRODUTO INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    PRECO DECIMAL(17,2),
    ID_CATEGORIA INTEGER,
    DESCRICAO VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS CATEGORIA_PRODUTO
(
    ID_CATEGORIA INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME_CATEGORIA VARCHAR(100)
);

/*criacao as FKs*/
